/* Generated with cbindgen:0.29.0 */

/* This file is automatically generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

extern "C" {

typedef struct ResultU64 {
	uint64_t value;
	char *error;
} ResultU64;

typedef struct ResultLonLat {
	double longitude;
	double latitude;
	char *error;
} ResultLonLat;

typedef struct LonLatDegrees {
	double lon;
	double lat;
} LonLatDegrees;

typedef struct LonLatDegreesArray {
	struct LonLatDegrees *data;
	uintptr_t len;
	char *error;
} LonLatDegreesArray;

typedef struct CellArray {
	uint64_t *data;
	uintptr_t len;
	char *error;
} CellArray;

struct ResultU64 a5_lon_lat_to_cell(double longitude, double latitude, int32_t resolution);

struct ResultU64 a5_cell_to_parent(uint64_t index, int32_t parent_resolution);

double a5_cell_area(int32_t resolution);

struct ResultLonLat a5_cell_to_lon_lat(uint64_t cell);

uint64_t a5_get_num_cells(int32_t resolution);

int32_t a5_get_resolution(uint64_t index);

void a5_free_lonlatdegrees_array(struct LonLatDegreesArray arr);

void a5_free_cell_array(struct CellArray arr);

struct LonLatDegreesArray a5_cell_to_boundary(uint64_t cell_id);

struct CellArray a5_cell_to_children(uint64_t index, int32_t child_resolution);

struct CellArray a5_get_res0_cells(void);
}