/* Generated with cbindgen:0.29.0 */

/* This file is automatically generated by cbindgen. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct ResultU64 {
  uint64_t value;
  char *error;
};

struct ResultLonLat {
  double longitude;
  double latitude;
  char *error;
};

struct LonLatDegrees {
  double lon;
  double lat;
};

struct LonLatDegreesArray {
  LonLatDegrees *data;
  uintptr_t len;
  char *error;
};

struct CellArray {
  uint64_t *data;
  uintptr_t len;
  char *error;
};

struct CellBoundaryOptions {
  bool closed_ring;
  /// Number of segments to use for each edge. Pass None to use the resolution of the cell (default: None)
  int32_t segments;
};

struct ResultSpherical {
  double theta;
  double phi;
  char *error;
};

extern "C" {

ResultU64 a5_lon_lat_to_cell(double longitude, double latitude, int32_t resolution);

ResultU64 a5_cell_to_parent(uint64_t index, int32_t parent_resolution);

double a5_cell_area(int32_t resolution);

ResultLonLat a5_cell_to_lon_lat(uint64_t cell);

uint64_t a5_get_num_cells(int32_t resolution);

int32_t a5_get_resolution(uint64_t index);

void a5_free_lonlatdegrees_array(LonLatDegreesArray arr);

void a5_free_cell_array(CellArray arr);

LonLatDegreesArray a5_cell_to_boundary(uint64_t cell_id, CellBoundaryOptions options);

CellArray a5_cell_to_children(uint64_t index, int32_t child_resolution);

CellArray a5_get_res0_cells();

CellArray a5_compact(const uint64_t *cells, uintptr_t len);

CellArray a5_uncompact(const uint64_t *cells, uintptr_t len, int32_t target_resolution);

void a5_free_string(char *ptr);

ResultU64 a5_hex_to_u64(const char *hex);

char *a5_u64_to_hex(uint64_t value);

uintptr_t a5_get_num_children(int32_t parent_res, int32_t child_res);

ResultSpherical a5_cell_to_spherical(uint64_t cell);

CellArray a5_spherical_cap(uint64_t cell_id, double radius);

CellArray a5_grid_disk(uint64_t cell_id, uintptr_t k);

CellArray a5_grid_disk_vertex(uint64_t cell_id, uintptr_t k);

}  // extern "C"
